"""fixed foreign key from servers.id to users.id

Revision ID: 6796bd6d1d10
Revises: b784d15da17e
Create Date: 2021-11-16 17:37:31.512080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6796bd6d1d10'
down_revision = 'b784d15da17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
