"""removed primary key from server_id in messages table

Revision ID: 77d2c6505c8b
Revises: da9bdd15fb31
Create Date: 2021-11-17 14:29:49.444837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d2c6505c8b'
down_revision = 'da9bdd15fb31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
