"""added content column to messages table

Revision ID: da9bdd15fb31
Revises: 92fa28e2d0e5
Create Date: 2021-11-17 14:21:09.292072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9bdd15fb31'
down_revision = '92fa28e2d0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###
